name: Build Intelcar APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Buscar ficheiros
        uses: actions/checkout@v4

      - name: Descompactar projeto
        run: |
          unzip -o Intelcar_2.7_PROJETO.zip
          ls -la

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Dar permissão ao Gradle
        run: chmod +x ./gradlew || true

      - name: Criar APK
        run: ./gradlew assembleDebug

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: Intelcar-APK
          path: app/build/outputs/apk/debug/*.apk
